### ISSUE TITLE
스터디 참여 희망자 리스트

### ISSUE THREAD

**Issue by SamTheKorean** [DaleStudy/english-interview#1]
1. https://github.com/SamTheKorean
2. https://github.com/yolophg
3. https://github.com/meoooh
4. https://github.com/dev-jonghoonpark
5. https://github.com/sounmind
6. https://github.com/bhyun-kim

**Comment by SamTheKorean** [comment]
스터디 참여 희망하시는 분들 아래 댓글에 깃허브 주소 부탁드릴게요~!

**Comment by say828** [comment]
참여 희망합니다!
https://github.com/saysimple0828
